Repository mulirow/desenvolvimento-de-software, pull requests merged in 2025-02, with the labels that each got.

#4 Add Analysis interface
  app/analysis/page.tsx
  tailwind.config.ts
Labels: enhancement

#23 docs: update read.me
  README.md
Labels: documentation

#26 Add project ADL and initial ADRs
  README.md
  adr/0000-use-markdown-adr.md
  adr/0001-use-nextjs-for-front-framework.md
  adr/0002-use-mongodb-for-database.md
  adr/0003-use-google-ai-studio-for-ai-api.md
  adr/0004-use-tailwind-css-for-front-stylization.md
Labels: documentation

#32 Refactor navbar
  components/Navbar.tsx
Labels: refactor
